swagger: '2.0'
info:
  title: Stawapp API
  description: API REST per il backend della web application.
  version: 1.0.0
host: 'mydevpc.csi.it:80'
schemes:
  - http
basePath: /rest/be
produces:
  - application/json
paths:
  /ping:
    get:
      operationId: ping
      summary: servizio di ping del backend
      description: Restituisce una stringa per confermare la disponibilità del backend
      produces:
        - plain/text
      tags:
        - TOH
      responses:
        '200':
          description: stringa di conferma funzionamento
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            type: string
  
